Add SPM. Resolve warnings due to Image deprecation.
RxSwiftCommunity/RxKingfisher pull request #23
Opened 2020-08-07 16:44 UTC by bigMOTOR

2020-08-07 16:52 UTC, bigMOTOR commented
@freak4pc Hi, Could you take a look, please. 
Have a nice day!

2020-08-08 06:01 UTC, freak4pc commented
Hey, did you check this actually works? There are some issues with SPM and RxSwift in some scenarios, see here:

https://bugs.swift.org/browse/SR-12303

2020-08-08 06:01 UTC, freak4pc commented
Also can you check what's wrong with C?

2020-08-08 09:26 UTC, bigMOTOR commented
@freak4pc Hi! Thank you for quick response. Sure it works. I live with SPM in prod, that is why I need SPM on this package )) I'm already switched to it on my branch.
I'll check CI? But do you have any idea `use of undeclared type 'KFCrossPlatformImage'` what could cause it because KFCrossPlatformImage valid type.

2020-11-28 19:13 UTC, bigMOTOR commented
@freak4pc Hi! I hope you are doing great. I fixed CI due to SPM way. Let's push it live, SPM is really a must nowadays. 🙌
Have a good day!

2020-12-03 22:15 UTC, freak4pc requested changes

2020-12-03 22:15 UTC, freak4pc commented on Package.swift
> +    // Targets can depend on other targets in this package, and on products in packages which this package depends on.
remove all the comments from this file

2020-12-03 22:15 UTC, freak4pc commented on Package.swift
> +    .package(url: "https://github.com/ReactiveX/RxSwift.git", .upToNextMajor(from: "5.1.1" )),
this should be 5.0.0 and up

2020-12-03 22:15 UTC, freak4pc commented on Package.swift
> +    .package(url: "https://github.com/onevcat/Kingfisher.git", .upToNextMajor(from: "5.15.7" )),
this should be 5.0.0 and up as well I believe unless there's a reason

2020-12-03 22:15 UTC, freak4pc commented on Sources/RxKingfisher/Kingfisher+Rx.swift
> +extension Reactive where Base == KingfisherWrapper<KFCrossPlatformImageView> {
if you have code changes to make you should do these in a separate PR, not this one - just to make sure we're reviewing things seperately. Thanks!

2020-12-03 22:15 UTC, freak4pc commented on Sources/RxKingfisher/Kingfisher+Rx.swift
>                      single(.success(value.image))
revert

2020-12-04 20:53 UTC, bigMOTOR commented
Hi @freak4pc 
Thank you for your comments. All issues are resolved now.

2021-01-02 10:19 UTC, freak4pc approved these changes

2021-01-02 10:19 UTC, merged